{% set version = '0.0-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-assertive.strings
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/assertive.strings_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/assertive.strings/assertive.strings_{{ version }}.tar.gz
  sha256: d541d608a01640347d661cc9a67af8202904142031a20caa270f1c83d0ccd258

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1004
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertive.base >=0.0_2
    - r-assertive.types
    - r-stringi
  run:
    - r-base
    - r-assertive.base >=0.0_2
    - r-assertive.types
    - r-stringi

test:
  commands:
    - $R -e "library('assertive.strings')"           # [not win]
    - "\"%R%\" -e \"library('assertive.strings')\""  # [win]

about:
  home: https://bitbucket.org/richierocks/assertive.strings
  license: GPL-3.0-or-later
  summary: A set of predicates and assertions for checking the properties of strings.  This is
    mainly for use by other package developers who want to include run-time testing
    features in their own packages.  End-users will usually want to use assertive directly.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
