travis:
  secure:
    BINSTAR_TOKEN: zaXy+X/pOtwa7oAl6FcnSCrMKrzU4topT1VaoYkpK4+7fuaBYVFbhITSnvdr2YkfaWsUbdL198afkXR5UQUANdYiWG7vLolwmMe5bljTP0X2B0wET3gHEUVGY1kZx4v93a89At2+5OyySaPh9ckDeUTxgAZfdBW0sKURMdT60hicxGYr/MnRtFDLrx7LcKD67gsLTwta1i+xLK4vlO+rrJMBo3ldRaJcEukd52avuQIhvlAA61GJ7su3dpVmBwFWII1Gr5zeBiy+99Cq3bsiTbid1RT/MG0eUwHnvjsOpFhl6jo7nXMAMcD4QF1jySaOdx0fmpDEzwTbDUTrgs3vbnC0x/UO0648XxUSGRru3BoReb9syfhxCABB2/aGq3YffZsBbeSJUWSVnyot7hzCObORFqKfnaxoB9hBS7QR5ETo1JvXvW16WjLq2yrVvjZUPiz6y0oaZkZsbabQhVKVO9/N8N1OOulyLLx6VkNnDPCVJqhefdYatjQHT9V9HWr0uMoDY6qEkDX4WMAWSjYzIQ0pmeo5JNoydqDuUDsSwkF0koJ2FhZ5Vl9sWh7s0sATbdwkHa69LQH3bu0zlnlFxyy99ZQq8WQiDlp1t+WX+JeMeua2wpNUDyDo/bKozaUdmtwBLftSo2/VOGARzRL88Io09JwhrccS3YLxAj1nOcM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
