travis:
  secure:
    BINSTAR_TOKEN: H2Zkrt14/nLgX/cgnuSSI58yxdVTHUaCWqkXS8bZKyfomyq1khFIdUYr49tYhCfxDCTo6ypYT1+cC1FxxC1TpbMwHdOhsiG8vLZLycaov3NqlpMijCcHOHdGSTZdLcQ3o8Nxx5uHBZp/+12jpn74kOXxvAsWfOQWEiihUcu5AGR91YgGnRSt/ZgMhnBMnrY1zJCcvLnUTt91kj6Q3JgtXDtbqxm/TTV77kujUFmvEMGVDLQPuaEI7qx84axIIGxTIPo21cKuF/qAPehbNGui12/QNp21Fl3cZ8ZrRasFvK43+P42dq77BJWA3P/dsEdksZnRAUkD3dIBmKG5UWVhbXfII6xIKsi8KSOVOd3HXtw+Se86z7xL9+sOKgjzJj/x6OwTOMXUb+qAk0flCqISp40dJ52i48pIEGC6YfK2Yoa5NYkoKMVi4aV1RWbHGU1oJyGuyiadKEuQr4Ukqfe73K8iiF+9XJU7pPr9TkUMFaPR5HJPiR2mHLasS5eyLey+gXeqWGLK24gUc1to4J+yF/27FlyZ9x8fEE/ga+RkrcIF5e5N+CU0vLVqWjN9u3tQ46YcbVdbqGMcSQgc54ze3GtHgXFL/tHG28XYLrjLaTsajCuTeBBCitFYgd7wRfL4HTybe2EHdIPJb6o+0JUZAKyCTYHuj+h0uZpX4hFpfbQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
