appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: 5CkCo9LVJYTsMnzvSqgoVfe1zpS6hPzk43zDI7TaAAPtKb6qA+oyXdkkH/36ibFul6VtXSGC9Pt4ujDBHE9/Fs4TlxWu3t2naWd3qfzlYDHovwRx4clULW3x2EshvfG1Q+6I/kd587t6bc0l/C8SpTZFYHgr07sqFj7G/tgUhDywFnKAbMTXF8K4spD6Z4OLgSLdL9R7auBZ4xtDvWT98++Nf/A7dL+U0zPBp9hkuBiSp885sbujwyXHALJg2le3frINENMyobG8IdOUoXhbGJw/7ot8BcxD07WKeEL3dZSR8FmGxaKLcdxjUGjoM/YtOpcxT5T/w4izFsbkEtlEH5vE4DdoyrxbEWNsHRTIuJcYzT77KUNVvr8lSL5nSWkU3Nm1Gy98kuF0GOL31CiJrH4gVT1+aKRFJRyzw97ilHJIFF0LabY6IN4qWYSfpKhPpbLpOkM8z97cXU3VMCHdLjeQPAhV6YDaP+SMHDZf4x7wyRCZBa5F1UQu5l22Mm412o1X2OmkSCvarGSU/on9aCMY4lHJV+asx2c13zwgg7Bzcl2lg2kABWrmAuyGHcMle8QBlqD2wdw2EhGnz6zB/c2pnrAIi+Zk7w0pjopPvKtsPwABZy2OPzvgasjbSvf4lLE76p9eziSysDLM0guIzxrD/VJkyLVRnw5sGT8dK04=}
bot:
  automerge: true
