travis:
  secure:
    BINSTAR_TOKEN: F2c9Sj9O96+tmN8W/ry0JyhE0QraIv9o1X4hCU+CyWXOupvDz3QD7NUHXeyeNrn1S1SM0pDamXlKlaXpsLnIJ8bA/7MvJr93O4ix/bn460cRHb18VWQQY49zZZh1kxbHMWZzowOhI3XYWHxZQKT+9YXHR3DMQVB40N2aQG1N1/P52Yd1m976uxOU+y58wH4oaomXPj5H4xDQwI7yf9DnusEg4sFDonQdprCbV80XnnwSliv4O9TDremmKDGa9qP/sDydtjmEMIaXx1SkneSFMpCrpHznJxCISoc0U4/p+SqFqUIgZMZHvmeDXegiqzG/j1/Vdl/m5NvqloCewPhBRwfzpziZ3htDmhdPM+vxOyHAw/jrIT+1LMjYZ5SwlC6epsXQnRodBQm2VqVb2NPhUCxWfL5W5z43O3eZxMV1pGj5ba+V/UGT3P5eS8mpEcNV0h/CswyCeizmvRFhx1mGXUNImxO86PIXJHoLePJfzxAVwxWDsGNvLLoIMQHyc+zsXR8msCZT08gp04ya6utc0IF/YjrWinmuN6sOdmIUcrBho3FiXSdXWAFJwbP7uKZy/hIb09zt4gp8/8Tv0okZYt5hwfng3egxEA/T/XHFFS4PDk2sAJB+Ax5iZ133fwIQDiwIesHx2pv746nqQMn/X/0j47kAzvWjrsLljG0zDQg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
